# Generated by Django 5.0.3 on 2024-03-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_manufacture_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacture',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='manufacture',
            name='warehouse',
            field=models.ManyToManyField(to='warehouse.warehouse'),
        ),
    ]
